ASGI text build
pacificclimate/wx-files-service pull request #26
Opened 2024-10-16 22:18 UTC by corviday

This is a test build for upgrading this repository to ASGI and connexion 3.

Questions:
* do we need an asgi framework like starlette, or does connexion fill that role?

2024-10-16 23:04 UTC, corviday commented
connexion [installs starlette](https://github.com/spec-first/connexion/blob/a930303faa9e10603cdd820c497303b2e52d8253/pyproject.toml#L56), so I am going to proceed on the assumption that we don't need a separate asgi framework.

2024-10-21 16:52 UTC, rod-glover requested changes
Nice clean job.

`setup.py` needs to die -- see comment below.

It seemed to take a very long time to load on the initial load. Spinner going. Second time was tolerable, about 3 s.  This might bear looking into?

2024-10-21 16:52 UTC, rod-glover commented on .github/workflows/python-ci.yml
> +    runs-on: ubuntu-22.04
Only one Python ver? It is possible (but more work :(( ) to use more than one python interpreter in Poetry. Maybe put that in a follow-on issue?

2024-10-21 16:52 UTC, rod-glover commented on docker/Dockerfile
> +CMD poetry run uvicorn --port 8000 --host 0.0.0.0 --reload wxfs.asgi:connexion_app
Yay, sooo much better to serve it with something proper. I can't believe I didn't use Gunicorn before.

2024-10-21 16:52 UTC, rod-glover commented on pyproject.toml
> +connexion = {extras = ["swagger-ui", "flask", "uvicon"], version = "^3.1.0"}
"`uvicon`" or "`uvicorn`"??

2024-10-21 16:52 UTC, rod-glover commented on setup.py
Everything in `setup.py` can (and should) be transferred into `pyproject.toml`, then `setup.py` consigned to the dustbin of history. Example in Met Data Portal: https://github.com/pacificclimate/station-data-portal-backend/blob/master/pyproject.toml

2024-10-21 22:05 UTC, corviday commented
I have gotten rid of `setup.py`. 

I think I saw a very slow page load at some point, but I can't reproduce it now.

2024-10-21 22:23 UTC, rod-glover approved these changes
Great, nice work!

2024-10-21 23:29 UTC, merged